### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by nneubauer** [pH14/graphmatch#1]
First of all, thanks for you gem, saving me half a work day at least. However I encountered some sort of bug. In certain situations the library seems to be stuck in an infinite loop. Sample input:

```
[
    [0] "1 0 i",
    [1] "1 1 love",
    [2] "1 2 you"
]

[
    [ 0] "2 0 that",
    [ 1] "2 1 mini",
    [ 2] "2 2 heart",
    [ 3] "2 3 attack",
    [ 4] "2 4 that",
    [ 5] "2 5 i",
    [ 6] "2 6 get",
    [ 7] "2 7 when",
    [ 8] "2 8 i",
    [ 9] "2 9 wake",
    [10] "2 10 up",
    [11] "2 11 late",
    [12] "2 12 and",
    [13] "2 13 then",
    [14] "2 14 i",
    [15] "2 15 realize",
    [16] "2 16 that",
    [17] "2 17 i's",
    [18] "2 18 my",
    [19] "2 19 free",
    [20] "2 20 day",
    [21] "2 21 xd"
]

{
       "1 0 i" => {
         "2 5 i" => -1,
         "2 8 i" => -1,
        "2 14 i" => -1
    },
    "1 1 love" => {
            "2 0 that" => -0.024449145356481072,
            "2 1 mini" => -0.000889146624543228,
           "2 2 heart" => -0.03503903895240424,
          "2 3 attack" => -0.0003105432641123415,
            "2 4 that" => -0.024449145356481072,
             "2 6 get" => -0.00901607535538627,
            "2 7 when" => -0.016400666345402236,
            "2 9 wake" => -0.0007939396978629007,
             "2 10 up" => -0.010684590913410862,
           "2 11 late" => -0.00165534736486594,
            "2 12 and" => -0.0372545299459328,
           "2 13 then" => -0.004685703554703055,
        "2 15 realize" => -0.0011484396267210251,
           "2 16 that" => -0.024449145356481072,
             "2 18 my" => -0.04726713666196249,
           "2 19 free" => -0.004948474924322938,
            "2 20 day" => -0.006535530098344709,
             "2 21 xd" => -1.4413695900592007e-06
    },
     "1 2 you" => {
            "2 0 that" => -0.3678332191388018,
            "2 1 mini" => -0.000520802526506881,
           "2 2 heart" => -0.008789212073545265,
          "2 3 attack" => -0.0062627658629557615,
            "2 4 that" => -0.3678332191388018,
             "2 6 get" => -0.24107801559838055,
            "2 7 when" => -0.07157101663673998,
            "2 9 wake" => -0.000783762085269008,
             "2 10 up" => -0.07845204060617658,
           "2 11 late" => -0.0010246884493954461,
            "2 12 and" => -0.09741805839136941,
           "2 13 then" => -0.09763454520634522,
        "2 15 realize" => -0.010586050862747037,
           "2 16 that" => -0.3678332191388018,
             "2 18 my" => -0.482606423352083,
           "2 19 free" => -0.03145482923112022,
            "2 20 day" => -0.011357644916840135,
             "2 21 xd" => -0.00011513689151788686
    }
}
```

First left_vertices, then right_vertices and then edges. This leads to said loop with this call stack (when canceling):

```
    from /Users/nneubauer/Desktop/graphmatch.rb:153:in `call'
    from /Users/nneubauer/Desktop/graphmatch.rb:153:in `augmenting_path'
    from /Users/nneubauer/Desktop/graphmatch.rb:125:in `block in best_matching!'
    from /Users/nneubauer/Desktop/graphmatch.rb:124:in `loop'
    from /Users/nneubauer/Desktop/graphmatch.rb:124:in `best_matching!'
    from /Users/nneubauer/Desktop/graphmatch.rb:46:in `match'
```

Any idea what's wrong?

PS: I also noticed that in a ruby 1.9.3 environment `gem install grahmatch` and followed by a `require 'graphmatch'` results in an error (some files not found, you might want to investigate, too).

**Comment by pH14** [comment]
Thanks reporting this. It's my first Ruby gem, so it's bound to have some problems.

I'll look into both of these shortly.

**Comment by pH14** [comment]
So I know where it's looping (stuck on the loop on lines 39-42 of maxflow.rb), but I'm not sure why. It has to do with the fact that all of the edges from "1 0 i" are negative and the same value.

Unfortunately I haven't been able to fix it so far. I have exams coming up so I won't be able to get to this for another week or so. Sorry, hope it's not too much of an inconvenience.

**Comment by nneubauer** [comment]
Thanks for your response. Would be grateful if you were to fix this bug. I made some tests with positive values (shifting all by adding +1) but the error persists.

**Comment by pH14** [comment]
Hi again,

So I had been looking through the code trying to find a bug, without considering what's actually going on here!

The matching algorithm is a modified version of the Ford-Fulkerson algorithm. Unfortunately, if the edge weights are irrational it's possible for FF to stall and be unable to find a matching. This is an unavoidable consequence of the algorithm itself. If all of your edges are integers, it will work. Hopefully you can scale your values to integers.

I'll add in an error message for when this case occurs and get to work on fixing the gem.
